### ISSUE TITLE
Decide and implement details of platform, memory layout, and I/O

### ISSUE THREAD

**Issue by naure** [scroll-tech/ceno#215]
The platform is the specification of how programs are loaded, what are the regions of memory, how I/O works, and more details.

The current draft is essentially this [platform.rs](https://github.com/scroll-tech/ceno/blob/master/ceno_emul/src/platform.rs), this [linker script](https://github.com/scroll-tech/ceno/blob/master/ceno_rt/ceno_link.x), and a [demo of MMIO](https://github.com/scroll-tech/ceno/blob/master/ceno_rt/src/io.rs).

**Comment by matthiasgoergens** [comment]
@naure What do you mean by 'virtual memory'?  I know the term in the context of real physical computers, but I don't know what it means in our context.

**Comment by matthiasgoergens** [comment]
> * Support panic as a valid outcome, and include the exit code as part of public I/O (see [Feat: Ecall/Halt #258](https://github.com/scroll-tech/ceno/pull/258)).

I'd rather not.  It's extra complexity that we don't need.

**Comment by naure** [comment]
I don't think this issue is closed; or it should have a follow up issue. We still need to apply the choices and in particular update the Platform type (replace rom/ram fields and such).

**Comment by matthiasgoergens** [comment]
> I don't think this issue is closed; or it should have a follow up issue. We still need to apply the choices and in particular update the Platform type (replace rom/ram fields and such).

I updated the title to say 'Decide and implement [...]' to make this issue its own follow-up and re-opened it.

**Comment by naure** [comment]
Implementation: https://github.com/scroll-tech/ceno/pull/735
