### ISSUE TITLE
Report circuit stats

### ISSUE THREAD

**Issue by kunxian-xia** [scroll-tech/ceno#553]

**Comment by hero78119** [comment]
To expand more, we probably need to have statistics tools for summary on 2 dimensions: per opcode/table circuit/overall

- number of constrains, and degree distribution
- number of witins

And per opcode circuit sorted by opcode frequency, where the frequency can retrieved from Fabonacci guest program traces.

**Comment by naure** [comment]
@mcalancea This data lives in [ConstraintSystem](https://github.com/scroll-tech/ceno/blob/d0d23a5cfb43c3f968f3e550cb45cd4f51df50fc/ceno_zkvm/src/circuit_builder.rs#L102).
