### ISSUE TITLE
Make the platform dynamic

### ISSUE THREAD

**Issue by naure** [scroll-tech/ceno#566]
Currently, platform details (e.g. special memory addresses) are constants, and guest programs must target it.

It’s possible to upgrade these constants to parameters chosen by guest programs. These parameters can be given in ELF files and/or CLI arguments.

To do it, replace all usages of the `CENO_PLATFORM` constant into a `platform: Platform` argument, like for example `VMState.platform` does. It might be harder than it sounds; did not try yet.

_Refs: [platform.rs](https://github.com/scroll-tech/ceno/blob/master/ceno_emul/src/platform.rs), [linker script](https://github.com/scroll-tech/ceno/blob/master/ceno_rt/ceno_link.x), etc._

_Related: #215, #378, #476._

**Comment by naure** [comment]
A number of these dependencies to Platform are being removed in #368.

A notable exception is `StaticMemTable::len()` and `PubIOTable::len()` which are currently hard-coded.

**Comment by mcalancea** [comment]
Yep.
