### ISSUE TITLE
Refactor `SetTableAddrType`

### ISSUE THREAD

**Issue by naure** [scroll-tech/ceno#573]
While adding memory and PI features, there has been some leakage of frontend concepts into the backend, which should only know about math, not VMs.

Some pointer: [`SetTableAddrType::DynamicAddr`](https://github.com/scroll-tech/ceno/blob/b472e95a849db3a4c1ee2b57070500c33750b2d9/ceno_zkvm/src/scheme/verifier.rs#L704)

This could be refactored into a new type of polynomial type, similar to `Constant`, `Fixed`, etc. Let’s say `Linear`.
Then the circuits can use Linear columns to do for example address ranges.

~Another problem is that this table specification is needed during circuit "**construction**", but it belongs more logically and conveniently to the **fixed table generation phase**. I don’t know how to fix that one yet, though.~ (already solved by `CircuitBuilder.params`)

**Comment by naure** [comment]
Alternatively, the lengths could stay in CircuitBuilder, but then let the API accept parameters by value like in #587.

**Comment by hero78119** [comment]
I raise another issue which is from backend perspective https://github.com/scroll-tech/ceno/issues/654
which also related to probably introduce a new type of polynomial to hold meta info of `SetTableAddrType`.

**Comment by naure** [comment]
Closing in favor of the more precise #654.
