### ISSUE TITLE
Refactor `RowMajorMatrix` with a safe API

### ISSUE THREAD

**Issue by naure** [scroll-tech/ceno#600]
This type uses `MaybeInit` with the expectation that assignment code will set values in every cell. Moreover, the matrix is usually larger than requested in `new(…)` because it is padded to a power-of-two size. All in all that is error-prone and hard to debug (been there, #597).

Rewrite this with a safe and easy API.

One idea is to use `Vec::with_capacity` and `extend`. Another way could be based on iterators and use `collect_vec`.

Regarding padding, the type should take the responsibility to fill the padding rows. It is not actually necessary to allocate that padding space. The padding can be represented with _a single value to repeat_, and the padding is done at the last possible time in `de_interleaving`. It could look like a method `set_padding_strategy(…)`, see the existing `enum InstancePaddingStrategy`.

**Comment by matthiasgoergens** [comment]
How much time or memory are we actually saving with the uninit shenanigans?

**Comment by naure** [comment]
The proposed approach should be marginally faster than the current one thanks to postponing the padding, but this issue is more about ease of use.

**Comment by matthiasgoergens** [comment]
Yes. I'm just curious how much we are gaining from the shenanigans currently in master compared to not doing anything special?

Do you know whether we ever did some benchmarks?

**Comment by naure** [comment]
There is only the one implementation as far as I know.

**Comment by matthiasgoergens** [comment]
> There is only the one implementation as far as I know.

That is we never did any benchmarks whether the unsafe shenanigans are doing anything for us?

Ok, I'm glad we are getting rid of them.
