### ISSUE TITLE
Fix absolute address of the end of hint input

### ISSUE THREAD

**Issue by matthiasgoergens** [scroll-tech/ceno#628]
https://github.com/scroll-tech/ceno/blob/matthias/ceno_host/ceno_host/src/lib.rs `test_rkyv_padding` has some example code to show that we can left-pad rkyv serialised data without any problems, but right padding doesn't work, at least not naively.

Thus we should fix the last byte of the input to always be in the same VM address, and make the start move further and further left, if we add more data.

See also https://github.com/scroll-tech/ceno/discussions/607 and https://github.com/scroll-tech/ceno/pull/622

**Comment by matthiasgoergens** [comment]
Have a look at the linked code for an example.

**Comment by matthiasgoergens** [comment]
> How does one use rkyv with the usual rightwards growth, like Vec or "write" APIs?

That would be interesting to look up!  But luckily it's irrelevant here.

> And what's the difference between left and right?

Have a look at the linked code.  Basically in rkyv: `chain(random garbage, your data)` is deserialisable, but `chain(your data, random garbage)` ain't.  You can replace 'random garbage' with 'memory addresses that throw an error when you try to access them'.

> I understand the difference between headers and footers in a streameable format, but I don't see how that applies here.

Luckily, we don't need to understand anything here.

**Comment by matthiasgoergens** [comment]
To make your life easier, let me copy and paste the relevant link from the docs in the code that I mentioned: https://rkyv.org/format.html

**Comment by naure** [comment]
> As long as your buffer ends right at the end of your root object

Ok sure that just means something else does the framing, i.e. keep track of the entry point. Just store the length in the first word then. Maybe the library actually has this feature already. That is when the data has to have a dynamic layout in the first place.

**Comment by matthiasgoergens** [comment]
> > As long as your buffer ends right at the end of your root object
> 
> Ok sure that just means something else does the framing (e.g. Rust slice length). Just store the length or entry point in the first word then. Maybe the library actually has this feature already. That is when the data has to have a dynamic layout in the first place.

No, that's not how it works.  Why do you think the start is more special than the end?

The library does not store the length or entry point at the start of the slice. What makes you think so?

(The experiments I linked you to wouldn't work, if it did.)

**Comment by matthiasgoergens** [comment]
To spell it out:

Rust slices have all the information necessary to determine eg their end, start, midpoint, length etc.

Rkyv's derserialisation expects to find a specific 'root' at a fixed offset from the end of the slice you pass it.

It then re-assembles the whole dag of your data structure from that root, by following pointers.

If you have some rkyv serialised data in a slice of absolute memory addresses of `start..end`, you can extend it to `earlier_start..end` and still get exactly the same data out, as long as `earlier_start <= start`.

Specifically in our case, we can fill the available hint input to always end at `end` when we prepare the VM's memory. Then we can ask rkyv to deserialise from `hint_io_start..end`, even if `hint_io_start` is much smaller than the actual start of the data in memory we prepared.

Does this make sense?

**Comment by naure** [comment]
This sounds like you have misinterpreted my last message which was admittedly compact, and assumed I didn’t know what I was talking about. I will try to expand some other time.

**Comment by matthiasgoergens** [comment]
Ok, thanks.

**Comment by matthiasgoergens** [comment]
@naure Please expand when you have time.

**Comment by naure** [comment]
Somebody has explained that solution: https://github.com/scroll-tech/ceno/pull/631#discussion_r1858437482
