### ISSUE TITLE
Write example program using hints

### ISSUE THREAD

**Issue by naure** [scroll-tech/ceno#639]
_Follow-up to #622_

Decide on and demonstrate a way to compile programs with hint memory such that the program and prover agree on the address range and content. See [design discussions](https://github.com/scroll-tech/ceno/discussions/607).

The first use-case is to replace the hard-coded input in [sproll-evm / include_bytes](https://github.com/scroll-tech/sproll-evm/pull/60/files#diff-e9ee652994a71824570e1348a7a2984f78cc7727141cf7dd0da5b1d1063ae1beR120)

**Comment by matthiasgoergens** [comment]
I reverse engineered @naure's code dump without his withheld assistance, and https://github.com/scroll-tech/ceno/pull/631 has the relevant code.

**Comment by naure** [comment]
Please avoid using my name that way. Thanks.

**Comment by matthiasgoergens** [comment]
> Please avoid using my name that way. Thanks.

Fixed it for you.
