### ISSUE TITLE
Precompile Architecture

### ISSUE THREAD

**Issue by naure** [scroll-tech/ceno#693]
Add the capability to support precompiles in the stack. Demonstrate with one precompile.

- [ ] #728 
  - [x] Including guest-side helper function.
- [ ] #727
- [ ] #729

**Comment by matthiasgoergens** [comment]
I suggest to demonstrate with a hash.

We will want to overhaul how the emulator handles ecalls. At the moment it seems to hardcode that every ecall gets to read a fixed number of registers? At least that's what the comments seem to imply.

**Comment by lispc** [comment]
seems a big task. Better to add some estimate dates of important sub tasks. @naure
