### ISSUE TITLE
Bug: fail to use InsnKind::SLTU in the lookup to program table for SLTU instruction

### ISSUE THREAD

**Issue by kunxian-xia** [scroll-tech/ceno#746]
When I tried to run the `sproll-evm` test using latest master branch, it fails with lots of lookup errors like this

```
ERROR ceno_zkvm::scheme::mock_prover: riscv_opcode/SLTU/fetch: value [Goldilocks(2ab85c), Goldilocks(9), Goldilocks(5), Goldilocks(c), Goldilocks(10), Goldilocks(0)] mismatch lk_multiplicity: real e6 > remaining 0 in Instruction table
```

You can reproduce this bug by the following cmd:
```
MOCK_PROVING=true RAYON_NUM_THREADS=32 RUST_LOG=info cargo run --package ceno_zkvm --bin e2e --release -- --platform=sp1 --hints ./poseidon_hint.bin riscv32im-succinct-zkvm-elf
```

**Comment by kunxian-xia** [comment]
This bug is caused by this line 
https://github.com/scroll-tech/ceno/blob/027f7b0baac71da6443f0cbb8cf557bcbe8e7a00/ceno_zkvm/src/instructions/riscv/slt.rs#L86

**Comment by zemse** [comment]
How is the `poseidon_hint.bin` built or how can I get it?

**Comment by kunxian-xia** [comment]
It's built inside a private repo. I can share with you offline.
